headers = {
            'User-Agent':
                "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36",
            'Accept-Language': 'uk'
        }


city_pages = {
    # "https://rieltor.ua/chabany/flats-sale/": {"city": "смт. Чабани", "url": "https://rieltor.ua/chabany/flats-sale/", "id": "17567"},
    "https://rieltor.ua/kotsjubinskoe-374/flats-sale/": {"city": "смт. Коцюбинське", "url": "https://rieltor.ua/kotsjubinskoe-374/flats-sale/", "id": "26873", 'region_id': 10},
    # "https://rieltor.ua/kozin-343/flats-sale/": {"city": "смт. Козин", "url": "https://rieltor.ua/kozin-343/flats-sale/", "id": "17641"},
    "https://rieltor.ua/gostomel/flats-sale/": {"city": "смт. Гостомель", "url": "https://rieltor.ua/gostomel/flats-sale/", "id": "17504", 'region_id': 10},
    # "https://rieltor.ua/glevaha/flats-sale/": {"city": "смт. Глеваха", "url": "https://rieltor.ua/glevaha/flats-sale/", "id": "17363"},
    # "https://rieltor.ua/vorzel/flats-sale/": {"city": "смт. Ворзель", "url": "https://rieltor.ua/vorzel/flats-sale/", "id": "17503"},
    "https://rieltor.ua/borodjanka/flats-sale/": {"city": "смт. Бородянка", "url": "https://rieltor.ua/borodjanka/flats-sale/", "id": "213", 'region_id': 10},
    # "https://rieltor.ua/jasnogorodka-57/flats-sale/": {"city": "с. Ясногородка", "url": "https://rieltor.ua/jasnogorodka-57/flats-sale/", "id": "17428"},
    # "https://rieltor.ua/jurjevka-41/flats-sale/": {"city": "с. Юрівка", "url": "https://rieltor.ua/jurjevka-41/flats-sale/", "id": "26906"},
    # "https://rieltor.ua/schastlivoe/flats-sale/": {"city": "с. Щасливе", "url": "https://rieltor.ua/schastlivoe/flats-sale/", "id": "17305"},
    # "https://rieltor.ua/chubinskoe/flats-sale/": {"city": "с. Чубинське", "url": "https://rieltor.ua/chubinskoe/flats-sale/", "id": "17306"},
    # "https://rieltor.ua/chajki-979/flats-sale/": {"city": "с. Чайки", "url": "https://rieltor.ua/chajki-979/flats-sale/", "id": "26679"},
    # "https://rieltor.ua/hotov/flats-sale/": {"city": "с. Хотів", "url": "https://rieltor.ua/hotov/flats-sale/", "id": "17566"},
    "https://rieltor.ua/hodosovka/flats-sale/": {"city": "с. Ходосівка", "url": "https://rieltor.ua/hodosovka/flats-sale/", "id": "17565", 'region_id': 10},
    "https://rieltor.ua/sofievskaja-borschagovka/flats-sale/": {"city": "с. Софіївська борщагівка", "url": "https://rieltor.ua/sofievskaja-borschagovka/flats-sale/", "id": "17563", 'region_id': 10},
    # "https://rieltor.ua/petrovskoe-676/flats-sale/": {"city": "с. Святопетрівське", "url": "https://rieltor.ua/petrovskoe-676/flats-sale/", "id": "27890"},
    # "https://rieltor.ua/rudnja-777/flats-sale/": {"city": "с. Рудня", "url": "https://rieltor.ua/rudnja-777/flats-sale/", "id": "17350"},
    # "https://rieltor.ua/revnoe/flats-sale/": {"city": "с. Ревне", "url": "https://rieltor.ua/revnoe/flats-sale/", "id": "17299"},
    # "https://rieltor.ua/podgortsy/flats-sale/": {"city": "с. Підгірці", "url": "https://rieltor.ua/podgortsy/flats-sale/", "id": "26875"},
    # "https://rieltor.ua/proleski/flats-sale/": {"city": "с. Проліски", "url": "https://rieltor.ua/proleski/flats-sale/", "id": "17297"},
    # "https://rieltor.ua/pogreby-685/flats-sale/": {"city": "с. Погреби", "url": "https://rieltor.ua/pogreby-685/flats-sale/", "id": "17346"},
    # "https://rieltor.ua/plesetskoe/flats-sale/": {"city": "с. Плесецьке", "url": "https://rieltor.ua/plesetskoe/flats-sale/", "id": "17385"},
    "https://rieltor.ua/petropavlovskaja-borschagovka/flats-sale/": {"city": "с. Петропавлівська борщагівка", "url": "https://rieltor.ua/petropavlovskaja-borschagovka/flats-sale/", "id": "17561", 'region_id': 10},
    # "https://rieltor.ua/novye-petrovtsy/flats-sale/": {"city": "с. Нові Петрівці", "url": "https://rieltor.ua/novye-petrovtsy/flats-sale/", "id": "17417"},
    # "https://rieltor.ua/novoselki-599/flats-sale/": {"city": "с. Новосілки", "url": "https://rieltor.ua/novoselki-599/flats-sale/", "id": "26874"},
    # "https://rieltor.ua/novoselki-485/flats-sale/": {"city": "с. Новосілки", "url": "https://rieltor.ua/novoselki-485/flats-sale/", "id": "26874"},
    # "https://rieltor.ua/novoselki-600/flats-sale/": {"city": "с. Новосілки", "url": "https://rieltor.ua/novoselki-600/flats-sale/", "id": "26874"},
    # "https://rieltor.ua/novoe/flats-sale/": {"city": "с. Нове", "url": "https://rieltor.ua/novoe/flats-sale/", "id": "26905"},
    # "https://rieltor.ua/milaja/flats-sale/": {"city": "с. Мила", "url": "https://rieltor.ua/milaja/flats-sale/", "id": "27219"},
    # "https://rieltor.ua/malaja-olshanka-499/flats-sale/": {"city": "с. Мала Вільшанка", "url": "https://rieltor.ua/malaja-olshanka-499/flats-sale/", "id": "17230"},
    # "https://rieltor.ua/krjukovschina/flats-sale/": {"city": "с. Крюківщина", "url": "https://rieltor.ua/krjukovschina/flats-sale/", "id": "17552"},
    # "https://rieltor.ua/kruglik/flats-sale/": {"city": "с. Круглик", "url": "https://rieltor.ua/kruglik/flats-sale/", "id": "27494"},
    # "https://rieltor.ua/krasilovka-378/flats-sale/": {"city": "с. Красилівка", "url": "https://rieltor.ua/krasilovka-378/flats-sale/", "id": "17340"},
    # "https://rieltor.ua/kozin-946/flats-sale/": {"city": "с. Козин", "url": "https://rieltor.ua/kozin-946/flats-sale/", "id": "17615"},
    # "https://rieltor.ua/zazimje/flats-sale/": {"city": "с. Зазим'я", "url": "https://rieltor.ua/zazimje/flats-sale/", "id": "17336"},
    # "https://rieltor.ua/demidov/flats-sale/": {"city": "с. Демидів", "url": "https://rieltor.ua/demidov/flats-sale/", "id": "17406"},
    # "https://rieltor.ua/gorenichi/flats-sale/": {"city": "с. Гореничі", "url": "https://rieltor.ua/gorenichi/flats-sale/", "id": "17546"},
    # "https://rieltor.ua/gora-132/flats-sale/": {"city": "с. Гора", "url": "https://rieltor.ua/gora-132/flats-sale/", "id": "17288"},
    # "https://rieltor.ua/gnedin/flats-sale/": {"city": "с. Гнідин", "url": "https://rieltor.ua/gnedin/flats-sale/", "id": "17286"},
    # "https://rieltor.ua/gnatovka/flats-sale/": {"city": "с. Гнатівка", "url": "https://rieltor.ua/gnatovka/flats-sale/", "id": "27498"},
    "https://rieltor.ua/gatnoe/flats-sale/": {"city": "с. Гатне", "url": "https://rieltor.ua/gatnoe/flats-sale/", "id": "17545", 'region_id': 10},
    # "https://rieltor.ua/gavrilovka/flats-sale/": {"city": "с. Гаврилівка", "url": "https://rieltor.ua/gavrilovka/flats-sale/", "id": "17404"},
    # "https://rieltor.ua/vita-pochtovaja/flats-sale/": {"city": "с. Віта-поштова", "url": "https://rieltor.ua/vita-pochtovaja/flats-sale/", "id": "17543"},
    # "https://rieltor.ua/vishnevoe-370/flats-sale/": {"city": "с. Вишневе", "url": "https://rieltor.ua/vishnevoe-370/flats-sale/", "id": "17544"},
    # "https://rieltor.ua/vishenki/flats-sale/": {"city": "с. Вишеньки", "url": "https://rieltor.ua/vishenki/flats-sale/", "id": "17283"},
    # "https://rieltor.ua/belogorodka/flats-sale/": {"city": "с. Білогородка", "url": "https://rieltor.ua/belogorodka/flats-sale/", "id": "17539"},
    # "https://rieltor.ua/bucha-525/flats-sale/": {"city": "с. Буча", "url": "https://rieltor.ua/bucha-525/flats-sale/", "id": "612"},
    # "https://rieltor.ua/buzovo/flats-sale/": {"city": "с. Бузова", "url": "https://rieltor.ua/buzovo/flats-sale/", "id": "17542"},
    # "https://rieltor.ua/fastov/flats-sale/": {"city": "Фастів", "url": "https://rieltor.ua/fastov/flats-sale/", "id": "234"},
    # "https://rieltor.ua/ukrainka/flats-sale/": {"city": "Українка", "url": "https://rieltor.ua/ukrainka/flats-sale/", "id": "17653"},
    # "https://rieltor.ua/obuhov/flats-sale/": {"city": "Обухів", "url": "https://rieltor.ua/obuhov/flats-sale/", "id": "225"},
    "https://rieltor.ua/flats-sale/": {"city": "Київ", "url": "https://rieltor.ua/flats-sale/", "id": "10", 'region_id': 10},
    # "https://rieltor.ua/vishnevoe-67/flats-sale/": {"city": "Вишневе", "url": "https://rieltor.ua/vishnevoe-67/flats-sale/", "id": "17544"},
    "https://rieltor.ua/vyshgorod/flats-sale/": {"city": "Вишгород", "url": "https://rieltor.ua/vyshgorod/flats-sale/", "id": "216", 'region_id': 10},
    # "https://rieltor.ua/belaja-tserkov/flats-sale/": {"city": "Біла Церква", "url": "https://rieltor.ua/belaja-tserkov/flats-sale/", "id": "210"},
    "https://rieltor.ua/bucha-239/flats-sale/": {"city": "Буча", "url": "https://rieltor.ua/bucha-239/flats-sale/", "id": "612", 'region_id': 10},
    "https://rieltor.ua/brovary/flats-sale/": {"city": "Бровари", "url": "https://rieltor.ua/brovary/flats-sale/", "id": "214", 'region_id': 10},
    # "https://rieltor.ua/bojarka/flats-sale/": {"city": "Боярка", "url": "https://rieltor.ua/bojarka/flats-sale/", "id": "17541"},
    # "https://rieltor.ua/borispol/flats-sale/": {"city": "Бориспіль", "url": "https://rieltor.ua/borispol/flats-sale/", "id": "212"},
    "https://rieltor.ua/irpen/flats-sale/": {"city": "Ірпінь", "url": "https://rieltor.ua/irpen/flats-sale/", "id": "220", 'region_id': 10},


    "https://rieltor.ua/harkov/flats-sale/": {"city": "Харків", "url": "https://rieltor.ua/harkov/flats-sale/", "id": "7", 'region_id': 7},
    "https://rieltor.ua/kamyanskoe/flats-sale/": {"city": "Кам'янське", "url": "https://rieltor.ua/kamyanskoe/flats-sale/", "id": "72", 'region_id': 11},
    "https://rieltor.ua/dnepr/flats-sale/": {"city": "Дніпро", "url": "https://rieltor.ua/dnepr/flats-sale/", "id": "11", 'region_id': 11},
    "https://rieltor.ua/poltava/flats-sale/": {"city": "Полтава", "url": "https://rieltor.ua/poltava/flats-sale/", "id": "20", 'region_id': 20},
    "https://rieltor.ua/zaporozhje/flats-sale/": {"city": "Запоріжжя", "url": "https://rieltor.ua/zaporozhje/flats-sale/", "id": "14", 'region_id': 14},
}